=== Bookrage001/IntroToSoftwareDevAssignment/IntroToSoftwareDevAssignment/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="username">
        <xs:restriction base="xs:string">
            <xs:maxLength value="12"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:minLength value="4"/>
            <xs:maxLength value="12"/>
            <xs:pattern value="[a-zA-z0-9\p{P}$\^\+=~`|]+" />
        </xs:restriction>
    </xs:simpleType>  
    
    <xs:simpleType name="address">
        <xs:restriction base="xs:string">
            <xs:minLength value="4"/>
            <xs:maxLength value="12"/>
            <xs:pattern value="[a-zA-z0-9\p{P}$\^\+=~`|]+" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="city">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-zA-Z]+)(\s[A-Z][a-zA-Z]+)+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="state">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-zA-Z]+)(\s[A-Z][a-zA-Z]+)+" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="postcode">
        <xs:restriction base="xs:string">
            <xs:maxLength value="4"/>
            <xs:pattern value="[0-9]" />
        </xs:restriction>
    </xs:simpleType>    
    
    <xs:simpleType name="phoneNo">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
            <xs:pattern value="[0-9]" />
        </xs:restriction>
    </xs:simpleType>    
    
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username" type="username"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="role" type="xs:string"/>
                            <xs:element name="address" type="address"/>
                            <xs:element name="city" type="city"/>
                            <xs:element name="state" type="state"/>
                            <xs:element name="postcode" type="postcode"/>
                            <xs:element name="phoneNo" type="phoneNo"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bookrage001/IntroToSoftwareDevAssignment/IntroToSoftwareDevAssignment/build/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="users.xsd">
    
    <user id="1"> 
        <username>mcanthony</username>
        <firstName>Mark</firstName>
        <lastName>Anthony</lastName>
        <email>mark.anthony@mail.com</email>
        <password>bueno</password>
        <role>Staff</role>
        <address>45 Brown Street</address>
        <city>North Sydney</city>
        <state>NSW</state> 
        <postcode>2060</postcode>
        <phoneNo>0493375418</phoneNo> 
    </user>
    
    <user id="2">
        <username>ardenc</username>
        <firstName>Caleb</firstName>
        <lastName>Arden</lastName>
        <email>caleb.arden@mail.com</email>
        <password>chocmilk</password>
        <role>Staff</role>  
        <address>49 Ocean Street</address>
        <city>Sydney South</city> 
        <state>NSW</state> 
        <postcode>2000</postcode>
        <phoneNo>0480821798</phoneNo>
    </user> 
    
    <user id="3"> 
        <username>hclaud</username>
        <firstName>Hayley</firstName>
        <lastName>Claud</lastName>
        <email>hayley.claud@mail.com</email>
        <password>ASDWER!!234.hdc</password>
        <role>Staff</role>
        <address>22 Queen Street</address>
        <city>Harbord</city> 
        <state>NSW</state> 
        <postcode>2096</postcode>
        <phoneNo>0425301619</phoneNo>
    </user> 
    
    <user id="4">
        <username>chungboii</username>
        <firstName>Sean</firstName>
        <lastName>Chung</lastName>
        <email>sean.chung@mail.com</email>
        <password>colourboi</password>
        <role>Staff</role>
        <address>8 Winbourne Street</address>
        <city>Dee Why</city>
        <state>NSW</state>
        <postcode>2099</postcode>
        <phoneNo>0417396453</phoneNo>
    </user> 
    
    <user id="5">
        <username>hsaab</username>
        <firstName>Husein</firstName>
        <lastName>Saab</lastName>
        <email>husein.saab@mail.com</email>
        <password>apple123</password>
        <role>Customer</role>
        <address>56 Quirk Road</address> 
        <city>Balgowlah</city>
        <state>NSW</state> 
        <postcode>2093</postcode>
        <phoneNo>0492738462</phoneNo>    
    </user> 
    
    <user id="6">
        <username>zchen</username>
        <firstName>Zihan</firstName>
        <lastName>Chen</lastName>
        <email>zihan.chen@mail.com</email>
        <password>zc1234</password>
        <role>Customer</role>
        <address>14 Koorala Street</address>
        <city>Manly Vale</city> 
        <state>NSW</state> 
        <postcode>2096</postcode>  
        <phoneNo>0456293647</phoneNo>
    </user>  
</Users>
