=== Bookrage001/IntroToSoftwareDevAssignment/IntroToSoftwareDevAssignment/build/web/users.xsd
<?xml version="1.0"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Insert your type declarations here -->
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="gender">
        <xs:restriction base="xs:string">
            <xs:maxLength value="6"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="age">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Insert your element declarations here -->
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence> 
                            <xs:element name="name" type="name"/>                  
                            <xs:element name="gender" type="radio"/>
                            <xs:element name="age" type="number"/>
                            <xs:element name="password" type="number"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bookrage001/IntroToSoftwareDevAssignment/IntroToSoftwareDevAssignment/build/web/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="movies.xsl"?>

<users    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="users.xsd">
          
    <user id="1">
        <name>Tom</name>
        <gender>male</gender>
        <age>23</age>
        <password>123456</password>
    </user>
    <user id="2">
        <name>Alva</name>
        <gender>female</gender>
        <age>20</age>
        <password>234567</password>
    </user>
    <user id="3">
        <name>Bob</name>
        <gender>male</gender>
        <age>22</age>
        <password>345678</password>
    </user>
    <user id="3">
        <name>Annablle</name>
        <gender>female</gender>
        <age>34</age>
        <password>456789</password>
    </user>
    <user id="4">
        <name>Edward</name>
        <gender>male</gender>
        <age>32</age>
        <password>567890</password>
    </user>
    <user id="5">
        <name>Cherry</name>
        <gender>female</gender>
        <age>30</age>
        <password>134566</password>
    </user>
    <user id="6">
        <name>Alan</name>
        <gender>male</gender>
        <age>29</age>
        <password>563386</password>
    </user>
    <user id="7">
        <name>Claire</name>
        <gender>female</gender>
        <age>33</age>
        <password>239568</password>
    </user>
     <user id="8">
        <name>Daisy</name>
        <gender>female</gender>
        <age>25</age>
        <password>263568</password>
    </user>
     <user id="9">
        <name>Tony</name>
        <gender>male</gender>
        <age>24</age>
        <password>133567</password>
    </user>
     <user id="10">
        <name>Helen</name>
        <gender>female</gender>
        <age>21</age>
        <password>324587</password>
    </user>
</users>
